In [61]:
import numpy as np
import pandas as pd
dataset = pd.read_csv('cleaned_emotion.csv')
x=dataset.drop(columns=['label'])
y=dataset['label']



In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [67]:
from sklearn.decomposition import PCA
pca = PCA(n_components= 3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [68]:
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[62 13 22]
 [47 35  8]
 [38 21 27]]


In [69]:
print('Accuracy')
print(accuracy_score(y_test, y_pred))

Accuracy
0.4542124542124542


In [71]:
principalDf = pd.DataFrame(dataset, columns=['A', 'B', 'C'])
finalDf = pd.concat([principalDf, y], axis=1)

finalDf.to_csv("pcadata.csv", index=False, header=True)  # save final df to a csv file

exvar = pca.explained_variance_ratio_
cexvarsum = np.cumsum(exvar)

print(exvar)

[0.49800529 0.17321805 0.14139098]
